### ISSUE TITLE
RE: too many commits

### ISSUE THREAD

**Issue by ochanje210** [sv-bootcamp/yoda#48]
you have over 300+ commits on master branch and it seems very hard to follow up by reading all those commit logs. Shouldn't you squash them somehow and only left important ones before moving on to V2?

**Comment by lyw0149** [comment]
https://github.com/blog/2141-squash-your-commits

@ethkim  @nlpenguin  @KaylaKwon @SarahhhC @djflexible

**Comment by ochanje210** [comment]
Yes and yes
