### ISSUE TITLE
Handle err when sending an email.

### ISSUE THREAD

**Issue by lyw0149** [sv-bootcamp/yoda#50]
We can
1. Store log in DB
2. Notify to slack dev_channel

or is there any idea??

I think this issue is related with how to check server status.

**Comment by heartjigi** [comment]
Is there no way to retry?

**Comment by SarahhhC** [comment]
Maybe we need both of them. We need to try fail when sending an email.

**Comment by ethkim** [comment]
We could store in the log and run a cron job to retry "all" failed messages daily.

This is potentially violating privacy (to store users' email messages in the log), but we can go from now and later think about encrypting these messages in the backend and only allow the cron job to decrypt prior to retrying.
